---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2021-05-26T21:27:24Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: spring-petclinic-cloud
    app.kubernetes.io/name: customers-db-mysql
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-26T21:27:24Z"
  name: data-customers-db-mysql-0
  namespace: spring-petclinic
  resourceVersion: "21159"
  uid: d2e25be2-1bce-4608-a6aa-4d1ecc2087eb
spec:
  storageClassName: "hostpath-provisioner"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
status:
  phase: Pending